export { default as Navbar} from './navbar/navbar'
export {default as Send} from './send/send'
export {default as Species} from './species/species'
export {default as About} from './about/about'
export {default as  Directions} from './directions/directions'
export {default as Footer} from './footer/footer'